services:
  server:
    container_name: fast_api_server
    ports:
      - 8000:80
    build:
      context: .
      dockerfile: "./code/Dockerfile"
    env_file: .env
    environment:
      GRANT_SUDO: "yes"
    volumes:
      - "./code/app:/code/app"
